### PR TITLE
Upgrate to webpack-blocks v1.0.0 and to support webpack 4

### PR DESCRIPTION
**Pull request by marcofugaro**
This PR rewrites the block using the new block structure and upgrades its dependencies such as ts-loader, which was giving problems with the new webpack

There seems to be an issue with the tests, sorry I couldn't understand what it was

### CODE REVIEW

**Comment by foxbunny** [comment]
Thanks for this. I no longer use it, so I'll just take your word for it. 😋

I'll release it tomorrow since I'm not at a computer right now.

**Comment by marcofugaro** [comment]
Did you publish a new version? 🙂

**Comment by foxbunny** [comment]
@marcofugaro Sorry about that. Slipped my mind. The 2.0.0 is up now. Incidentally, if you want to adopt this package, I would be glad to arrange it.

**Comment by marcofugaro** [comment]
Sure thing man, add me as a mantainer!

**Comment by foxbunny** [comment]
@marcofugaro I've sent you an invitation on NPM. Hopefully that works, I've never done this type of thing before. :)

**Comment by marcofugaro** [comment]
Yup, I have it in [my profile](https://www.npmjs.com/~marcofugaro), thank you! 🙌

**Pull request merged**
